#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../.." && pwd)"
output_path="${repo_root}/.env.test.local"
mode="tunnel"

usage() {
  cat <<'EOF' >&2
usage: write_test_env.sh [--mode tunnel|private] [--output <path>]

Writes a gitignored shell env file for DB-backed test suites using the current
Terraform outputs. The file contains app-level disposable test DB URLs, not a
local PostgreSQL instance.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode)
      mode="${2:-}"
      shift 2
      ;;
    --output)
      output_path="${2:-}"
      shift 2
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done

case "${mode}" in
  tunnel|private)
    ;;
  *)
    echo "Unsupported mode: ${mode}" >&2
    usage
    exit 1
    ;;
esac

require_command() {
  local name="$1"
  if ! command -v "${name}" >/dev/null 2>&1; then
    echo "Required command not found: ${name}" >&2
    exit 1
  fi
}

require_command terraform
require_command python3

terraform_json="$(terraform -chdir="${repo_root}/infra" output -json)"

mapfile -t env_lines < <(
  MODE="${mode}" TERRAFORM_OUTPUT_JSON="${terraform_json}" python3 - <<'PY'
import json
import os
import shlex

payload = json.loads(os.environ["TERRAFORM_OUTPUT_JSON"])
mode = os.environ["MODE"]

db_user = payload["db_user"]["value"]
db_password = payload["db_password"]["value"]
db_private_ip = payload["db_private_ip"]["value"]
bot_public_ip = payload["bot_public_ip"]["value"]

if mode == "tunnel":
    test_host = "127.0.0.1"
    test_port = 15432
else:
    test_host = db_private_ip
    test_port = 5432

test_db = "qpi_test"
scratch_db = "qpi_test_scratch"

def quote(value: str) -> str:
    return shlex.quote(value)

test_url = f"postgresql://{db_user}:{db_password}@{test_host}:{test_port}/{test_db}"
scratch_url = f"postgresql://{db_user}:{db_password}@{test_host}:{test_port}/{scratch_db}"

print("# Generated by scripts/dev/write_test_env.sh from local Terraform outputs.")
print("# Safe to source locally; do not commit this file.")
print(f"export TEST_DATABASE_URL={quote(test_url)}")
print(f"export TEST_SCRATCH_DATABASE_URL={quote(scratch_url)}")
print(f"export QPI_DB_VM_HOST={quote(db_private_ip)}")
if mode == "tunnel":
    print(f"export QPI_DB_VM_SSH_PROXY_HOST={quote(bot_public_ip)}")
    print("export QPI_DB_VM_SSH_PROXY_USER=ubuntu")
print("# Optional override if your DB VM SSH key is not ~/.ssh/id_rsa:")
print("# export QPI_DB_VM_SSH_KEY_PATH=/path/to/private/key")
PY
)

mkdir -p "$(dirname "${output_path}")"
printf '%s\n' "${env_lines[@]}" > "${output_path}"

cat <<EOF
Wrote ${output_path}

Load it with:
  source ${output_path}

Mode: ${mode}
EOF
