services:
  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command:
      - redis-server
      - --save
      - ""
      - --appendonly
      - "no"
      - --maxmemory
      - 512mb
      - --maxmemory-policy
      - allkeys-lru
    ports:
      - "6379:6379"
