services:
  supportbot:
    image: ${SUPPORT_BOT_IMAGE}
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command:
      - redis-server
      - --save
      - ""
      - --appendonly
      - "no"
      - --maxmemory
      - 512mb
      - --maxmemory-policy
      - allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
