name: Deploy Daily Report Scrapper

on:
  push:
    branches: ["main"]
    paths:
      - "services/daily_report_scrapper/**"
      - "libs/**"
      - "schema/**"
      - "pyproject.toml"
      - ".github/workflows/deploy_daily_report_scrapper.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: e-comet/yc_function_deploy_action@v1
        name: Deploy function
        with:
          service_account_key: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
          aws_access_key_id: ${{ secrets.YC_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.YC_AWS_SECRET_ACCESS_KEY }}
          bucket_name: "code-deploy"
          function_id: ${{ secrets.YC_DAILY_REPORT_CF_ID }}
          function_entrypoint: "services.daily_report_scrapper.main.handler"
          function_runtime: "python312"
          source: "."
          exclude: ".git,.github,.pytest_cache,.ruff_cache,qpi.egg-info,infra"
